import mongoose, { Document, Schema, Model } from 'mongoose';

export type TaskType = 'call' | 'email' | 'meeting' | 'follow_up' | 'review' | 'other';
export type TaskStatus = 'open' | 'in_progress' | 'completed' | 'cancelled' | 'snoozed';
export type TaskPriority = 'low' | 'normal' | 'high' | 'urgent';

export interface ITask extends Document {
  _id: mongoose.Types.ObjectId;
  clientId: mongoose.Types.ObjectId;
  title: string;
  description?: string;
  taskType: TaskType;
  status: TaskStatus;
  priority: TaskPriority;
  assignedTo?: mongoose.Types.ObjectId;
  dueAt: Date;
  slaPolicyId?: mongoose.Types.ObjectId;
  slaDeadline?: Date;
  slaTargetMinutes: number;
  slaBreached: boolean;
  slaBreachedAt?: Date;
  firstResponseAt?: Date;
  completedAt?: Date;
  completedBy?: mongoose.Types.ObjectId;
  completionNotes?: string;
  disposition?: string;
  snoozedUntil?: Date;
  leadId?: mongoose.Types.ObjectId;
  contactId?: mongoose.Types.ObjectId;
  conversationId?: mongoose.Types.ObjectId;
  formSubmissionId?: mongoose.Types.ObjectId;
  campaignId?: mongoose.Types.ObjectId;
  idempotencyKey?: string;
  isAutoGenerated: boolean;
  createdBy?: mongoose.Types.ObjectId;
  updatedBy?: mongoose.Types.ObjectId;
  isCustomerVisible: boolean;
  customerActionRequired: boolean;
  customerActionDescription?: string;
  customerCompletedAt?: Date;
  metadata: Record<string, any>;
  createdAt: Date;
  updatedAt: Date;
}

const TaskSchema = new Schema<ITask>(
  {
    clientId: {
      type: Schema.Types.ObjectId,
      ref: 'Client',
      required: true,
      index: true,
    },
    title: {
      type: String,
      required: true,
      trim: true,
    },
    description: {
      type: String,
      trim: true,
    },
    taskType: {
      type: String,
      enum: ['call', 'email', 'meeting', 'follow_up', 'review', 'other'],
      default: 'follow_up',
      index: true,
    },
    status: {
      type: String,
      enum: ['open', 'in_progress', 'completed', 'cancelled', 'snoozed'],
      default: 'open',
      index: true,
    },
    priority: {
      type: String,
      enum: ['low', 'normal', 'high', 'urgent'],
      default: 'normal',
      index: true,
    },
    assignedTo: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      index: true,
    },
    dueAt: {
      type: Date,
      required: true,
      index: true,
    },
    slaPolicyId: {
      type: Schema.Types.ObjectId,
      ref: 'SlaPolicy',
    },
    slaDeadline: {
      type: Date,
      index: true,
    },
    slaTargetMinutes: {
      type: Number,
      default: 240,
    },
    slaBreached: {
      type: Boolean,
      default: false,
      index: true,
    },
    slaBreachedAt: {
      type: Date,
    },
    firstResponseAt: {
      type: Date,
    },
    completedAt: {
      type: Date,
    },
    completedBy: {
      type: Schema.Types.ObjectId,
      ref: 'User',
    },
    completionNotes: {
      type: String,
      trim: true,
    },
    disposition: {
      type: String,
      trim: true,
      index: true,
    },
    snoozedUntil: {
      type: Date,
    },
    leadId: {
      type: Schema.Types.ObjectId,
      ref: 'Lead',
      index: true,
    },
    contactId: {
      type: Schema.Types.ObjectId,
      ref: 'Contact',
      index: true,
    },
    conversationId: {
      type: Schema.Types.ObjectId,
      ref: 'Conversation',
      index: true,
    },
    formSubmissionId: {
      type: Schema.Types.ObjectId,
      ref: 'FormSubmission',
      index: true,
    },
    campaignId: {
      type: Schema.Types.ObjectId,
      ref: 'AdCampaign',
      index: true,
    },
    idempotencyKey: {
      type: String,
      trim: true,
    },
    isAutoGenerated: {
      type: Boolean,
      default: false,
    },
    createdBy: {
      type: Schema.Types.ObjectId,
      ref: 'User',
    },
    updatedBy: {
      type: Schema.Types.ObjectId,
      ref: 'User',
    },
    isCustomerVisible: {
      type: Boolean,
      default: false,
      index: true,
    },
    customerActionRequired: {
      type: Boolean,
      default: false,
    },
    customerActionDescription: {
      type: String,
      trim: true,
    },
    customerCompletedAt: {
      type: Date,
    },
    metadata: {
      type: Schema.Types.Mixed,
      default: {},
    },
  },
  {
    timestamps: true,
  }
);

// Tenant-scoped Compound Indexes
TaskSchema.index({ clientId: 1, status: 1, dueAt: 1 });
TaskSchema.index({ clientId: 1, assignedTo: 1, status: 1 });
TaskSchema.index({ clientId: 1, priority: 1, dueAt: 1 });
TaskSchema.index({ clientId: 1, slaBreached: 1, slaDeadline: 1 });
TaskSchema.index({ clientId: 1, isCustomerVisible: 1, contactId: 1 });
TaskSchema.index({ clientId: 1, isCustomerVisible: 1, leadId: 1 });
TaskSchema.index(
  { clientId: 1, idempotencyKey: 1 },
  { unique: true, partialFilterExpression: { idempotencyKey: { $type: 'string' } } }
);

export const Task: Model<ITask> =
  mongoose.models.Task || mongoose.model<ITask>('Task', TaskSchema);
