import mongoose from 'mongoose';
import { IWorkflowAction, IWorkflow } from '../models/Workflow';
import { IWorkflowRun } from '../models/WorkflowRun';
import { Task } from '../models/Task';
import { Lead } from '../models/Lead';
import { ClientMembership } from '../models/ClientMembership';
import { TaskService } from './task.service';
import { TaskAssignmentService } from './taskAssignment.service';
import { LeadActivityService } from './leadActivity.service';
import { NotificationService } from './notification.service';
import { ProviderManager } from './providers/provider.manager';
import { logger } from '../config/logger';

export interface IActionResultSummary {
  actionId: string;
  actionType: string;
  status: 'success' | 'failed' | 'skipped';
  output?: any;
  error?: string;
  executedAt: Date;
  durationMs: number;
}

export class ActionExecutor {
  /**
   * Helper to safely replace template variables like {{lead.fullName}} or {{lead.email}}
   */
  public static interpolateTemplate(text: string, context: Record<string, any>): string {
    if (!text || typeof text !== 'string') return '';
    return text.replace(/\{\{\s*([a-zA-Z0-9_.]+)\s*\}\}/g, (_, path) => {
      const parts = path.split('.');
      let current: any = context;
      for (const part of parts) {
        if (current === null || current === undefined) return '';
        current = current[part];
      }
      return current !== undefined && current !== null ? String(current) : '';
    });
  }

  /**
   * Executes a single workflow action step with idempotency and isolation safeguards.
   */
  public static async executeAction(
    action: IWorkflowAction,
    workflow: IWorkflow,
    run: IWorkflowRun,
    eventContext: Record<string, any>
  ): Promise<IActionResultSummary> {
    const startTime = Date.now();
    const clientIdStr = workflow.clientId.toString();

    try {
      let output: any = null;

      switch (action.type) {
        case 'create_task': {
          const payload = action.payload || {};
          const title = this.interpolateTemplate(payload.title || 'Automated Follow-up Task', eventContext);
          const description = this.interpolateTemplate(payload.description || '', eventContext);
          const taskType = payload.taskType || 'follow_up';
          const priority = payload.priority || 'normal';
          const dueHours = Number(payload.dueInHours) || (Number(payload.dueInDays) ? Number(payload.dueInDays) * 24 : 24);
          const dueAt = new Date(Date.now() + dueHours * 60 * 60 * 1000);

          // Resolve entity links from event context or payload
          const leadId = payload.leadId || eventContext.lead?._id || eventContext.leadId;
          const contactId = payload.contactId || eventContext.contact?._id || eventContext.contactId;

          // Side-effect idempotency: check if task was already created for this run & action
          const idempotencyKey = `wf_${run._id}_task_${action.id}`;
          const existingTask = await Task.findOne({
            clientId: workflow.clientId,
            idempotencyKey,
          });

          if (existingTask) {
            output = { taskId: existingTask._id.toString(), reused: true, title: existingTask.title };
            break;
          }

          const newTask = await TaskService.createTask(
            clientIdStr,
            {
              title,
              description,
              taskType,
              priority,
              assignedTo: payload.assignedTo || undefined,
              leadId: leadId ? leadId.toString() : undefined,
              contactId: contactId ? contactId.toString() : undefined,
              dueAt,
              idempotencyKey,
              isAutoGenerated: true,
              metadata: {
                workflowId: workflow._id.toString(),
                workflowRunId: run._id.toString(),
                actionId: action.id,
              },
            },
            {
              id: this.getSafeActorId(workflow, eventContext),
              name: 'Workflow Engine',
            }
          );

          output = { taskId: newTask._id.toString(), title: newTask.title, status: newTask.status };
          break;
        }

        case 'assign_task': {
          const payload = action.payload || {};
          const taskId = payload.taskId || eventContext.task?._id || eventContext.taskId;
          if (!taskId) {
            throw new Error('Task ID is required for assign_task action');
          }
          if (!payload.assignedTo) {
            throw new Error('Target assignedTo user ID is required for assign_task action');
          }

          const assignedTask = await TaskAssignmentService.assignTask(
            clientIdStr,
            taskId.toString(),
            payload.assignedTo.toString(),
            {
              id: this.getSafeActorId(workflow, eventContext),
              name: 'Workflow Engine',
            },
            payload.reason || `Automated via workflow: ${workflow.name}`
          );

          output = { taskId: assignedTask._id.toString(), assignedTo: payload.assignedTo };
          break;
        }

        case 'update_lead_stage': {
          const payload = action.payload || {};
          const leadId = payload.leadId || eventContext.lead?._id || eventContext.leadId;
          if (!leadId) {
            throw new Error('Lead ID is required for update_lead_stage action');
          }
          const targetStage = payload.stage;
          if (!targetStage) {
            throw new Error('Target stage is required for update_lead_stage action');
          }

          const lead = await Lead.findOne({ _id: leadId, clientId: workflow.clientId });
          if (!lead) {
            throw new Error(`Lead ${leadId} not found in client workspace`);
          }

          const previousStage = lead.stage;
          if (previousStage !== targetStage) {
            lead.stage = targetStage;
            await lead.save();

            // Log timeline activity
            await LeadActivityService.log({
              leadId: lead._id,
              clientId: workflow.clientId,
              activityType: 'stage_changed',
              description: `Lead stage changed from ${previousStage} to ${targetStage} via workflow [${workflow.name}]`,
              metadata: {
                previousStage,
                newStage: targetStage,
                workflowId: workflow._id.toString(),
                workflowRunId: run._id.toString(),
              },
            });
          }

          output = { leadId: lead._id.toString(), previousStage, newStage: targetStage };
          break;
        }

        case 'add_crm_note': {
          const payload = action.payload || {};
          const leadId = payload.leadId || eventContext.lead?._id || eventContext.leadId;
          if (!leadId) {
            throw new Error('Lead ID is required for add_crm_note action');
          }
          const rawNote = payload.note || payload.content || '';
          const noteText = this.interpolateTemplate(rawNote, eventContext).trim().slice(0, 2000);
          if (!noteText) {
            throw new Error('Note content cannot be empty');
          }

          // Side-effect idempotency: verify not already added for this run & action
          const leadObjectId = new mongoose.Types.ObjectId(leadId.toString());
          const existingActivity = await mongoose.model('LeadActivity').findOne({
            leadId: leadObjectId,
            clientId: workflow.clientId,
            'metadata.workflowRunId': run._id.toString(),
            'metadata.actionId': action.id,
          });

          if (existingActivity) {
            output = { activityId: existingActivity._id.toString(), reused: true };
            break;
          }

          const activity = await LeadActivityService.log({
            leadId: leadObjectId,
            clientId: workflow.clientId,
            activityType: 'note_added',
            description: noteText,
            metadata: {
              source: 'workflow',
              workflowId: workflow._id.toString(),
              workflowRunId: run._id.toString(),
              actionId: action.id,
            },
          });

          output = { activityId: activity._id.toString(), leadId: leadId.toString() };
          break;
        }

        case 'add_tag': {
          const payload = action.payload || {};
          const leadId = payload.leadId || eventContext.lead?._id || eventContext.leadId;
          if (!leadId) {
            throw new Error('Lead ID is required for add_tag action');
          }
          const rawTag = payload.tag || payload.tagName;
          if (!rawTag || typeof rawTag !== 'string') {
            throw new Error('Valid tag string is required for add_tag action');
          }
          const cleanTag = rawTag.trim().toLowerCase().slice(0, 50);

          // Atomic & naturally idempotent $addToSet
          const updated = await Lead.findOneAndUpdate(
            { _id: leadId, clientId: workflow.clientId },
            { $addToSet: { tags: cleanTag } },
            { new: true }
          );

          if (!updated) {
            throw new Error(`Lead ${leadId} not found`);
          }

          output = { leadId: leadId.toString(), addedTag: cleanTag, tagsCount: updated.tags?.length || 0 };
          break;
        }

        case 'create_notification': {
          const payload = action.payload || {};
          const title = this.interpolateTemplate(payload.title || 'Workflow Alert', eventContext).slice(0, 200);
          const message = this.interpolateTemplate(payload.message || 'Automated operational notification', eventContext).slice(0, 2000);
          const severity = payload.severity || 'info';

          // Resolve recipient
          let recipientId = payload.recipientUserId;
          if (!recipientId || recipientId === 'assigned_user') {
            recipientId = eventContext.task?.assignedTo || eventContext.lead?.assignedTo;
          }

          // Fallback: If no assigned user, notify workspace admins
          if (!recipientId || recipientId === 'all_admins') {
            const adminMemberships = await ClientMembership.find({
              clientId: workflow.clientId,
              status: 'active',
            }).limit(5);

            const notifIds: string[] = [];
            for (const m of adminMemberships) {
              const n = await NotificationService.createNotification({
                clientId: workflow.clientId,
                recipientUserId: m.userId,
                type: 'workflow_alert',
                title,
                message,
                severity,
                sourceType: 'workflow_run',
                sourceId: run._id.toString(),
                metadata: {
                  workflowId: workflow._id.toString(),
                  workflowRunId: run._id.toString(),
                  actionId: action.id,
                },
              });
              notifIds.push(n._id.toString());
            }
            output = { notificationCount: notifIds.length, recipientUserIds: adminMemberships.map((m) => m.userId.toString()) };
            break;
          }

          const notification = await NotificationService.createNotification({
            clientId: workflow.clientId,
            recipientUserId: recipientId,
            type: 'workflow_alert',
            title,
            message,
            severity,
            sourceType: 'workflow_run',
            sourceId: run._id.toString(),
            metadata: {
              workflowId: workflow._id.toString(),
              workflowRunId: run._id.toString(),
              actionId: action.id,
            },
          });

          output = { notificationId: notification._id.toString(), recipientUserId: recipientId.toString() };
          break;
        }

        case 'send_email': {
          const payload = action.payload || {};
          const rawTo = payload.to || 'lead_email';
          let recipientEmail = '';

          // 1. Resolve recipient address from event context or payload
          if (rawTo === 'lead_email' || rawTo === '{{lead.email}}') {
            recipientEmail = (eventContext.lead?.email || eventContext.email || '').toLowerCase().trim();
          } else if (rawTo === 'contact_email' || rawTo === '{{contact.email}}') {
            recipientEmail = (eventContext.contact?.email || '').toLowerCase().trim();
          } else {
            recipientEmail = this.interpolateTemplate(rawTo, eventContext).toLowerCase().trim();
          }

          // 2. Email recipient format validation
          const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
          if (!recipientEmail || !emailRegex.test(recipientEmail)) {
            throw new Error(`Invalid recipient email address: '${recipientEmail}'`);
          }

          // 3. Email Safeguard (Correction 6): Explicit opt-in verification
          // Can only send to lead/contact in context OR an active workspace staff member.
          // Disallows sending to arbitrary external addresses.
          const leadEmail = (eventContext.lead?.email || '').toLowerCase().trim();
          const contactEmail = (eventContext.contact?.email || '').toLowerCase().trim();
          const isContextRecipient = recipientEmail === leadEmail || recipientEmail === contactEmail;

          let isWorkspaceMember = false;
          if (!isContextRecipient) {
            const memberMatch = await ClientMembership.findOne({
              clientId: workflow.clientId,
              status: 'active',
            }).populate({
              path: 'userId',
              match: { email: recipientEmail },
            });
            isWorkspaceMember = !!(memberMatch && memberMatch.userId);
          }

          if (!isContextRecipient && !isWorkspaceMember) {
            throw new Error(
              `Email policy violation: Recipient '${recipientEmail}' is neither the target lead/contact nor a verified workspace team member.`
            );
          }

          // 4. Message length limits
          const rawSubject = payload.subject || 'Notice from flumenxConectOS';
          const subject = this.interpolateTemplate(rawSubject, eventContext).trim().slice(0, 200);
          const rawBody = payload.body || payload.message || '';
          const body = this.interpolateTemplate(rawBody, eventContext).trim().slice(0, 5000);

          if (!body) {
            throw new Error('Email body content cannot be empty');
          }

          // 5. Check Provider Availability & Dispatch via Carrier Manager
          const provider = await ProviderManager.getProvider(clientIdStr, 'email');
          const emailIdempotencyKey = `wf_${run._id}_email_${action.id}`;

          const sendResult = await provider.sendMessage({
            to: recipientEmail,
            channel: 'email',
            body: `Subject: ${subject}\n\n${body}`,
            idempotencyKey: emailIdempotencyKey,
            metadata: {
              subject,
              workflowId: workflow._id.toString(),
              workflowRunId: run._id.toString(),
              actionId: action.id,
            },
          });

          if (!sendResult.success) {
            throw new Error(sendResult.failureReason || 'Email delivery failed at carrier layer');
          }

          output = {
            recipientEmail,
            subject,
            deliveryStatus: sendResult.deliveryStatus,
            externalMessageId: sendResult.externalMessageId,
          };
          break;
        }

        case 'schedule_follow_up': {
          const payload = action.payload || {};
          const title = this.interpolateTemplate(payload.title || 'Scheduled Follow-up', eventContext);
          const delayMinutes = Number(payload.delayMinutes) || 60;
          const dueAt = new Date(Date.now() + delayMinutes * 60 * 1000);
          const leadId = payload.leadId || eventContext.lead?._id || eventContext.leadId;

          const idempotencyKey = `wf_${run._id}_followup_${action.id}`;
          const existing = await Task.findOne({ clientId: workflow.clientId, idempotencyKey });
          if (existing) {
            output = { taskId: existing._id.toString(), reused: true, dueAt: existing.dueAt };
            break;
          }

          const followupTask = await TaskService.createTask(
            clientIdStr,
            {
              title,
              description: payload.notes || `Scheduled via workflow [${workflow.name}]`,
              taskType: 'follow_up',
              priority: payload.priority || 'normal',
              assignedTo: payload.assignedTo || undefined,
              leadId: leadId ? leadId.toString() : undefined,
              dueAt,
              idempotencyKey,
              isAutoGenerated: true,
              metadata: {
                workflowId: workflow._id.toString(),
                workflowRunId: run._id.toString(),
                actionId: action.id,
              },
            },
            {
              id: this.getSafeActorId(workflow, eventContext),
              name: 'Workflow Engine',
            }
          );

          output = { taskId: followupTask._id.toString(), dueAt: followupTask.dueAt };
          break;
        }

        case 'pause_workflow': {
          workflow.status = 'paused';
          await workflow.save();
          output = { workflowId: workflow._id.toString(), newStatus: 'paused' };
          break;
        }

        default:
          throw new Error(`Unsupported workflow action type: ${(action as any).type}`);
      }

      return {
        actionId: action.id,
        actionType: action.type,
        status: 'success',
        output,
        executedAt: new Date(),
        durationMs: Date.now() - startTime,
      };
    } catch (err: any) {
      logger.error(`Workflow action ${action.id} (${action.type}) failed:`, err);
      return {
        actionId: action.id,
        actionType: action.type,
        status: 'failed',
        error: err.message || 'Action execution failed',
        executedAt: new Date(),
        durationMs: Date.now() - startTime,
      };
    }
  }

  /**
   * Safely resolves actor ID handling unpopulated ObjectId or populated User object.
   */
  private static getSafeActorId(workflow: IWorkflow, eventContext: Record<string, any>): string | undefined {
    const raw = (workflow.createdBy as any)?._id
      ? (workflow.createdBy as any)._id.toString()
      : workflow.createdBy
      ? workflow.createdBy.toString()
      : eventContext.actor?.id;

    return raw && mongoose.Types.ObjectId.isValid(raw) ? raw : undefined;
  }
}
