import mongoose from 'mongoose';
import { Task, ITask, TaskStatus, TaskPriority, TaskType } from '../models/Task';
import { TaskEvent } from '../models/TaskEvent';
import { SlaService } from './sla.service';
import { TaskAssignmentService } from './taskAssignment.service';
import { EventDispatcher } from './eventDispatcher.service';
import { AppError } from '../middleware/errorHandler';

export interface CreateTaskDto {
  title: string;
  description?: string;
  taskType?: TaskType;
  priority?: TaskPriority;
  dueAt: Date;
  assignedTo?: string;
  leadId?: string;
  contactId?: string;
  conversationId?: string;
  formSubmissionId?: string;
  campaignId?: string;
  idempotencyKey?: string;
  isAutoGenerated?: boolean;
  isCustomerVisible?: boolean;
  customerActionRequired?: boolean;
  customerActionDescription?: string;
  metadata?: Record<string, any>;
}

export interface UpdateTaskDto {
  title?: string;
  description?: string;
  taskType?: TaskType;
  priority?: TaskPriority;
  dueAt?: Date;
  status?: TaskStatus;
  completionNotes?: string;
  isCustomerVisible?: boolean;
  customerActionRequired?: boolean;
  customerActionDescription?: string;
  metadata?: Record<string, any>;
}

export interface TaskFilterOptions {
  status?: string;
  priority?: string;
  taskType?: string;
  assignedTo?: string;
  leadId?: string;
  contactId?: string;
  conversationId?: string;
  slaBreached?: string;
  dueFrom?: string;
  dueTo?: string;
  search?: string;
  page?: number;
  limit?: number;
}

export class TaskService {
  /**
   * Creates a new task with tenant isolation, SLA deadline calculation, and event logging.
   */
  static async createTask(
    clientId: string,
    data: CreateTaskDto,
    actor?: { id?: string; name?: string }
  ): Promise<ITask> {
    const clientObjectId = new mongoose.Types.ObjectId(clientId);
    const priority = data.priority || 'normal';

    // 1. Calculate SLA deadline from current time (SLA target window)
    const { deadline, policyId, targetMinutes } = await SlaService.calculateSlaDeadline(
      clientId,
      priority,
      new Date()
    );

    // 2. Validate assignee if specified
    let assignedUserId: mongoose.Types.ObjectId | undefined;
    if (data.assignedTo) {
      const user = await TaskAssignmentService.validateActiveAssignee(clientId, data.assignedTo);
      assignedUserId = user._id;
    }

    // 3. Create Task
    const task = await Task.create({
      clientId: clientObjectId,
      title: data.title.trim(),
      description: data.description?.trim(),
      taskType: data.taskType || 'follow_up',
      status: 'open',
      priority,
      assignedTo: assignedUserId,
      dueAt: data.dueAt,
      slaPolicyId: policyId,
      slaDeadline: deadline,
      slaTargetMinutes: targetMinutes,
      leadId: data.leadId && mongoose.Types.ObjectId.isValid(data.leadId) ? new mongoose.Types.ObjectId(data.leadId) : undefined,
      contactId: data.contactId && mongoose.Types.ObjectId.isValid(data.contactId) ? new mongoose.Types.ObjectId(data.contactId) : undefined,
      conversationId: data.conversationId && mongoose.Types.ObjectId.isValid(data.conversationId) ? new mongoose.Types.ObjectId(data.conversationId) : undefined,
      formSubmissionId: data.formSubmissionId && mongoose.Types.ObjectId.isValid(data.formSubmissionId) ? new mongoose.Types.ObjectId(data.formSubmissionId) : undefined,
      campaignId: data.campaignId && mongoose.Types.ObjectId.isValid(data.campaignId) ? new mongoose.Types.ObjectId(data.campaignId) : undefined,
      idempotencyKey: data.idempotencyKey?.trim(),
      isAutoGenerated: data.isAutoGenerated || false,
      isCustomerVisible: data.isCustomerVisible || false,
      customerActionRequired: data.customerActionRequired || false,
      customerActionDescription: data.customerActionDescription?.trim(),
      createdBy: actor?.id && mongoose.Types.ObjectId.isValid(actor.id) ? new mongoose.Types.ObjectId(actor.id) : undefined,
      metadata: data.metadata || {},
    });

    // 4. Log Creation Event
    await TaskEvent.create({
      clientId: clientObjectId,
      taskId: task._id,
      eventType: 'created',
      description: `Task created by ${actor?.name || 'User'}`,
      newValue: {
        title: task.title,
        priority: task.priority,
        dueAt: task.dueAt,
        assignedTo: assignedUserId?.toString(),
      },
      actorId: actor?.id && mongoose.Types.ObjectId.isValid(actor.id) ? new mongoose.Types.ObjectId(actor.id) : undefined,
      actorName: actor?.name,
    });

    // Dispatch workflow trigger event: task.created
    try {
      await EventDispatcher.dispatch({
        clientId: task.clientId.toString(),
        eventType: 'task.created',
        eventId: `task_created_${task._id}`,
        entityId: task._id.toString(),
        entityType: 'task',
        payload: {
          task: task.toObject ? task.toObject() : task,
          priority: task.priority,
          taskType: task.taskType,
          leadId: task.leadId?.toString(),
          contactId: task.contactId?.toString(),
        },
        actor,
      });
    } catch (eventErr) {
      // Non-fatal
    }

    return task;
  }

  /**
   * Retrieves single task with on-demand SLA evaluation and entity population.
   */
  static async getTaskById(clientId: string, taskId: string): Promise<any> {
    const clientObjectId = new mongoose.Types.ObjectId(clientId);
    const taskObjectId = new mongoose.Types.ObjectId(taskId);

    const task = await Task.findOne({
      _id: taskObjectId,
      clientId: clientObjectId,
    })
      .populate('assignedTo', 'name email avatarUrl status')
      .populate('leadId', 'fullName email phone stage companyName')
      .populate('contactId', 'name email phone')
      .populate('conversationId', 'subject status priority channel')
      .populate('createdBy', 'name email');

    if (!task) {
      throw new AppError('Task not found', 404);
    }

    const slaEvaluation = SlaService.calculateTaskSla(task);
    return {
      ...task.toObject(),
      sla: slaEvaluation,
    };
  }

  /**
   * Lists tasks with search, multiple filters, dynamic SLA checks, and pagination.
   */
  static async listTasks(
    clientId: string,
    filter: TaskFilterOptions
  ): Promise<{ tasks: any[]; total: number; page: number; totalPages: number }> {
    const clientObjectId = new mongoose.Types.ObjectId(clientId);

    // Periodically update SLA breach statuses for open tasks
    await SlaService.checkAndMarkBreaches(clientId);

    const query: any = { clientId: clientObjectId };

    if (filter.status && filter.status !== 'all') {
      query.status = filter.status;
    }
    if (filter.priority && filter.priority !== 'all') {
      query.priority = filter.priority;
    }
    if (filter.taskType && filter.taskType !== 'all') {
      query.taskType = filter.taskType;
    }
    if (filter.assignedTo && filter.assignedTo !== 'all') {
      if (filter.assignedTo === 'unassigned') {
        query.assignedTo = { $exists: false };
      } else {
        query.assignedTo = new mongoose.Types.ObjectId(filter.assignedTo);
      }
    }
    if (filter.leadId) {
      query.leadId = new mongoose.Types.ObjectId(filter.leadId);
    }
    if (filter.contactId) {
      query.contactId = new mongoose.Types.ObjectId(filter.contactId);
    }
    if (filter.conversationId) {
      query.conversationId = new mongoose.Types.ObjectId(filter.conversationId);
    }
    if (filter.slaBreached === 'true') {
      query.slaBreached = true;
    } else if (filter.slaBreached === 'false') {
      query.slaBreached = false;
    }

    if (filter.dueFrom || filter.dueTo) {
      query.dueAt = {};
      if (filter.dueFrom) query.dueAt.$gte = new Date(filter.dueFrom);
      if (filter.dueTo) query.dueAt.$lte = new Date(filter.dueTo);
    }

    if (filter.search) {
      query.$or = [
        { title: { $regex: filter.search, $options: 'i' } },
        { description: { $regex: filter.search, $options: 'i' } },
      ];
    }

    const page = Math.max(1, filter.page || 1);
    const limit = Math.min(100, Math.max(1, filter.limit || 20));
    const skip = (page - 1) * limit;

    const [tasks, total] = await Promise.all([
      Task.find(query)
        .sort({ dueAt: 1, priority: -1 })
        .skip(skip)
        .limit(limit)
        .populate('assignedTo', 'name email avatarUrl')
        .populate('leadId', 'fullName email phone stage')
        .populate('contactId', 'name email phone')
        .lean(),
      Task.countDocuments(query),
    ]);

    // Enhance each task with dynamic SLA remaining time
    const enhanced = tasks.map((t: any) => {
      const sla = SlaService.calculateTaskSla(t as any);
      return {
        ...t,
        sla,
      };
    });

    return {
      tasks: enhanced,
      total,
      page,
      totalPages: Math.ceil(total / limit),
    };
  }

  /**
   * Updates task attributes and logs event.
   */
  static async updateTask(
    clientId: string,
    taskId: string,
    data: UpdateTaskDto,
    actor?: { id?: string; name?: string }
  ): Promise<ITask> {
    const clientObjectId = new mongoose.Types.ObjectId(clientId);
    const taskObjectId = new mongoose.Types.ObjectId(taskId);

    const task = await Task.findOne({ _id: taskObjectId, clientId: clientObjectId });
    if (!task) {
      throw new AppError('Task not found', 404);
    }

    const previousValue = {
      title: task.title,
      priority: task.priority,
      dueAt: task.dueAt,
      status: task.status,
    };

    if (data.title) task.title = data.title.trim();
    if (data.description !== undefined) task.description = data.description?.trim();
    if (data.taskType) task.taskType = data.taskType;
    if (data.status) task.status = data.status;
    if (data.completionNotes) task.completionNotes = data.completionNotes.trim();

    // Priority or Due Date change triggers SLA recalculation
    if (data.priority && data.priority !== task.priority) {
      task.priority = data.priority;
      const { deadline, targetMinutes } = await SlaService.calculateSlaDeadline(
        clientId,
        data.priority,
        task.createdAt
      );
      task.slaDeadline = deadline;
      task.slaTargetMinutes = targetMinutes;
    }

    if (data.dueAt) {
      task.dueAt = data.dueAt;
    }

    if (data.isCustomerVisible !== undefined) task.isCustomerVisible = data.isCustomerVisible;
    if (data.customerActionRequired !== undefined) task.customerActionRequired = data.customerActionRequired;
    if (data.customerActionDescription !== undefined) task.customerActionDescription = data.customerActionDescription?.trim();

    task.updatedBy = actor?.id ? new mongoose.Types.ObjectId(actor.id) : undefined;
    await task.save();

    await TaskEvent.create({
      clientId: clientObjectId,
      taskId: task._id,
      eventType: data.priority ? 'priority_changed' : data.dueAt ? 'due_date_changed' : 'status_changed',
      description: `Task updated by ${actor?.name || 'User'}`,
      previousValue,
      newValue: {
        title: task.title,
        priority: task.priority,
        dueAt: task.dueAt,
        status: task.status,
      },
      actorId: actor?.id ? new mongoose.Types.ObjectId(actor.id) : undefined,
      actorName: actor?.name,
    });

    return task;
  }

  /**
   * Starts a task (moves to in_progress, records first response time).
   */
  static async startTask(
    clientId: string,
    taskId: string,
    actor?: { id?: string; name?: string }
  ): Promise<ITask> {
    const task = await Task.findOne({
      _id: new mongoose.Types.ObjectId(taskId),
      clientId: new mongoose.Types.ObjectId(clientId),
    });

    if (!task) {
      throw new AppError('Task not found', 404);
    }

    const now = new Date();
    task.status = 'in_progress';
    if (!task.firstResponseAt) {
      task.firstResponseAt = now;
    }
    task.updatedBy = actor?.id ? new mongoose.Types.ObjectId(actor.id) : undefined;
    await task.save();

    await TaskEvent.create({
      clientId: new mongoose.Types.ObjectId(clientId),
      taskId: task._id,
      eventType: 'status_changed',
      description: `Task marked in progress by ${actor?.name || 'User'}`,
      newValue: { status: 'in_progress', firstResponseAt: now },
      actorId: actor?.id ? new mongoose.Types.ObjectId(actor.id) : undefined,
      actorName: actor?.name,
    });

    return task;
  }

  /**
   * Completes a task.
   */
  static async completeTask(
    clientId: string,
    taskId: string,
    completionNotes?: string,
    actor?: { id?: string; name?: string }
  ): Promise<ITask> {
    const task = await Task.findOne({
      _id: new mongoose.Types.ObjectId(taskId),
      clientId: new mongoose.Types.ObjectId(clientId),
    });

    if (!task) {
      throw new AppError('Task not found', 404);
    }

    const now = new Date();
    task.status = 'completed';
    task.completedAt = now;
    task.completedBy = actor?.id ? new mongoose.Types.ObjectId(actor.id) : undefined;
    if (completionNotes) task.completionNotes = completionNotes.trim();

    if (task.slaDeadline && now > task.slaDeadline) {
      task.slaBreached = true;
      if (!task.slaBreachedAt) task.slaBreachedAt = task.slaDeadline;
    }

    task.updatedBy = actor?.id ? new mongoose.Types.ObjectId(actor.id) : undefined;
    await task.save();

    await TaskEvent.create({
      clientId: new mongoose.Types.ObjectId(clientId),
      taskId: task._id,
      eventType: 'completed',
      description: `Task completed by ${actor?.name || 'User'}`,
      newValue: { status: 'completed', completedAt: now, completionNotes },
      actorId: actor?.id ? new mongoose.Types.ObjectId(actor.id) : undefined,
      actorName: actor?.name,
    });

    // Dispatch workflow trigger event: task.completed
    try {
      await EventDispatcher.dispatch({
        clientId: task.clientId.toString(),
        eventType: 'task.completed',
        eventId: `task_completed_${task._id}_${Date.now()}`,
        entityId: task._id.toString(),
        entityType: 'task',
        payload: {
          task: task.toObject ? task.toObject() : task,
          completionNotes,
          completedAt: now,
        },
        actor,
      });
    } catch (eventErr) {
      // Non-fatal
    }

    return task;
  }

  /**
   * Cancels a task.
   */
  static async cancelTask(
    clientId: string,
    taskId: string,
    reason?: string,
    actor?: { id?: string; name?: string }
  ): Promise<ITask> {
    const task = await Task.findOne({
      _id: new mongoose.Types.ObjectId(taskId),
      clientId: new mongoose.Types.ObjectId(clientId),
    });

    if (!task) {
      throw new AppError('Task not found', 404);
    }

    task.status = 'cancelled';
    if (reason) task.completionNotes = `Cancelled: ${reason.trim()}`;
    task.updatedBy = actor?.id ? new mongoose.Types.ObjectId(actor.id) : undefined;
    await task.save();

    await TaskEvent.create({
      clientId: new mongoose.Types.ObjectId(clientId),
      taskId: task._id,
      eventType: 'cancelled',
      description: `Task cancelled by ${actor?.name || 'User'}${reason ? `: ${reason}` : ''}`,
      newValue: { status: 'cancelled' },
      actorId: actor?.id ? new mongoose.Types.ObjectId(actor.id) : undefined,
      actorName: actor?.name,
    });

    return task;
  }

  /**
   * Snoozes a task until a future timestamp.
   */
  static async snoozeTask(
    clientId: string,
    taskId: string,
    snoozedUntil: Date,
    reason?: string,
    actor?: { id?: string; name?: string }
  ): Promise<ITask> {
    const task = await Task.findOne({
      _id: new mongoose.Types.ObjectId(taskId),
      clientId: new mongoose.Types.ObjectId(clientId),
    });

    if (!task) {
      throw new AppError('Task not found', 404);
    }

    task.status = 'snoozed';
    task.snoozedUntil = snoozedUntil;
    task.dueAt = snoozedUntil;
    task.updatedBy = actor?.id ? new mongoose.Types.ObjectId(actor.id) : undefined;
    await task.save();

    await TaskEvent.create({
      clientId: new mongoose.Types.ObjectId(clientId),
      taskId: task._id,
      eventType: 'snoozed',
      description: `Task snoozed until ${snoozedUntil.toISOString()} by ${actor?.name || 'User'}${reason ? `: ${reason}` : ''}`,
      newValue: { status: 'snoozed', snoozedUntil },
      actorId: actor?.id ? new mongoose.Types.ObjectId(actor.id) : undefined,
      actorName: actor?.name,
    });

    return task;
  }

  /**
   * Retrieves chronological audit event history for a task.
   */
  static async getTaskEvents(clientId: string, taskId: string) {
    return TaskEvent.find({
      clientId: new mongoose.Types.ObjectId(clientId),
      taskId: new mongoose.Types.ObjectId(taskId),
    }).sort({ createdAt: -1 });
  }

  /**
   * Returns aggregated task counts and SLA KPI metrics for a workspace.
   */
  static async getTaskKpis(clientId: string): Promise<{
    open: number;
    openTasks?: number;
    inProgress: number;
    inProgressTasks?: number;
    dueToday: number;
    overdue: number;
    overdueTasks?: number;
    slaBreached: number;
    slaBreachedTasks?: number;
    completedToday: number;
    total: number;
  }> {
    const clientObjectId = new mongoose.Types.ObjectId(clientId);
    const now = new Date();

    const startOfToday = new Date(now.getFullYear(), now.getMonth(), now.getDate());
    const endOfToday = new Date(now.getFullYear(), now.getMonth(), now.getDate(), 23, 59, 59, 999);

    await SlaService.checkAndMarkBreaches(clientId);

    const [open, inProgress, dueToday, overdue, slaBreached, completedToday, total] = await Promise.all([
      Task.countDocuments({ clientId: clientObjectId, status: 'open' }),
      Task.countDocuments({ clientId: clientObjectId, status: 'in_progress' }),
      Task.countDocuments({
        clientId: clientObjectId,
        status: { $in: ['open', 'in_progress', 'snoozed'] },
        dueAt: { $gte: startOfToday, $lte: endOfToday },
      }),
      Task.countDocuments({
        clientId: clientObjectId,
        status: { $in: ['open', 'in_progress', 'snoozed'] },
        dueAt: { $lt: now },
      }),
      Task.countDocuments({
        clientId: clientObjectId,
        status: { $in: ['open', 'in_progress', 'snoozed'] },
        slaBreached: true,
      }),
      Task.countDocuments({
        clientId: clientObjectId,
        status: 'completed',
        completedAt: { $gte: startOfToday, $lte: endOfToday },
      }),
      Task.countDocuments({ clientId: clientObjectId }),
    ]);

    return {
      open,
      openTasks: open,
      inProgress,
      inProgressTasks: inProgress,
      dueToday,
      overdue,
      overdueTasks: overdue,
      slaBreached,
      slaBreachedTasks: slaBreached,
      completedToday,
      total,
    };
  }

  /**
   * Daily Agenda: groups tasks into overdue, today, tomorrow, and upcoming.
   */
  static async getAgenda(clientId: string): Promise<{
    overdue: any[];
    today: any[];
    dueToday: any[];
    tomorrow: any[];
    dueTomorrow: any[];
    upcoming: any[];
  }> {
    const clientObjectId = new mongoose.Types.ObjectId(clientId);
    const now = new Date();

    const startOfToday = new Date(now.getFullYear(), now.getMonth(), now.getDate());
    const endOfToday = new Date(now.getFullYear(), now.getMonth(), now.getDate(), 23, 59, 59, 999);

    const startOfTomorrow = new Date(startOfToday.getTime() + 24 * 60 * 60 * 1000);
    const endOfTomorrow = new Date(endOfToday.getTime() + 24 * 60 * 60 * 1000);

    const activeTasks = await Task.find({
      clientId: clientObjectId,
      status: { $in: ['open', 'in_progress', 'snoozed'] },
    })
      .sort({ dueAt: 1, priority: -1 })
      .populate('assignedTo', 'name email avatarUrl')
      .populate('leadId', 'fullName email phone stage')
      .lean();

    const overdue: any[] = [];
    const today: any[] = [];
    const tomorrow: any[] = [];
    const upcoming: any[] = [];

    for (const t of activeTasks) {
      const due = new Date(t.dueAt);
      const enhanced = {
        ...t,
        sla: SlaService.calculateTaskSla(t as any),
      };

      if (due < now) {
        overdue.push(enhanced);
      } else if (due >= startOfToday && due <= endOfToday) {
        today.push(enhanced);
      } else if (due >= startOfTomorrow && due <= endOfTomorrow) {
        tomorrow.push(enhanced);
      } else {
        upcoming.push(enhanced);
      }
    }

    return {
      overdue,
      today,
      dueToday: today,
      tomorrow,
      dueTomorrow: tomorrow,
      upcoming,
    };
  }
}
