import mongoose from 'mongoose';
import { Task, ITask, TaskPriority } from '../models/Task';
import { TaskEvent } from '../models/TaskEvent';
import { SlaService } from './sla.service';
import { TaskAssignmentService, AssignmentStrategy } from './taskAssignment.service';
import { logger } from '../config/logger';

export interface GenerateLeadFollowUpParams {
  clientId: string | mongoose.Types.ObjectId;
  leadId: string | mongoose.Types.ObjectId;
  contactId?: string | mongoose.Types.ObjectId;
  conversationId?: string | mongoose.Types.ObjectId;
  formSubmissionId?: string | mongoose.Types.ObjectId;
  campaignId?: string | mongoose.Types.ObjectId;
  source: 'website_form' | 'webhook' | 'manual' | 'ad_attribution' | 'other';
  leadName: string;
  leadEmail?: string;
  leadPhone?: string;
  leadScore?: number;
  notes?: string;
  actorId?: string;
  strategy?: AssignmentStrategy;
}

export class TaskAutoFollowupService {
  /**
   * Automatically generates an initial follow-up task when an inbound lead arrives.
   * Enforces strict idempotency: duplicate calls for the same lead return the existing task.
   */
  static async generateLeadFollowUpTask(params: GenerateLeadFollowUpParams): Promise<ITask> {
    const {
      clientId,
      leadId,
      contactId,
      conversationId,
      formSubmissionId,
      campaignId,
      source,
      leadName,
      leadEmail,
      leadPhone,
      leadScore = 50,
      notes,
      actorId,
      strategy = 'least_open_tasks',
    } = params;

    const clientObjectId = new mongoose.Types.ObjectId(clientId.toString());
    const leadObjectId = new mongoose.Types.ObjectId(leadId.toString());
    const idempotencyKey = `lead_followup_${clientObjectId.toString()}_${leadObjectId.toString()}`;

    // 1. Idempotency Check: prevent duplicate follow-up task generation
    const existingTask = await Task.findOne({
      clientId: clientObjectId,
      idempotencyKey,
    });

    if (existingTask) {
      logger.info(`Idempotent follow-up task check: Task ${existingTask._id} already exists for lead ${leadObjectId}`);
      return existingTask;
    }

    // 2. Determine Priority & SLA Target
    let priority: TaskPriority = 'normal';
    if (leadScore >= 80 || source === 'ad_attribution' || source === 'website_form') {
      priority = 'urgent'; // 15-minute SLA target
    } else if (leadScore >= 50 || source === 'webhook') {
      priority = 'high'; // 1-hour SLA target
    }

    const now = new Date();
    const { deadline, policyId, targetMinutes } = await SlaService.calculateSlaDeadline(
      clientObjectId.toString(),
      priority,
      now
    );

    // 3. Resolve Assignee
    const assignedUserId = await TaskAssignmentService.resolveAutoAssignee(
      clientObjectId.toString(),
      strategy
    );

    // 4. Create Task
    const title = `Inbound Lead Follow-up: ${leadName}`;
    const description = [
      `New lead captured via ${source.replace('_', ' ').toUpperCase()}.`,
      leadEmail ? `Email: ${leadEmail}` : null,
      leadPhone ? `Phone: ${leadPhone}` : null,
      notes ? `Notes: ${notes}` : null,
    ]
      .filter(Boolean)
      .join('\n');

    const dueAt = deadline; // Auto-generated follow-up is due by SLA deadline

    const task = await Task.create({
      clientId: clientObjectId,
      title,
      description,
      taskType: 'follow_up',
      status: 'open',
      priority,
      assignedTo: assignedUserId,
      dueAt,
      slaPolicyId: policyId,
      slaDeadline: deadline,
      slaTargetMinutes: targetMinutes,
      slaBreached: false,
      leadId: leadObjectId,
      contactId: contactId ? new mongoose.Types.ObjectId(contactId.toString()) : undefined,
      conversationId: conversationId ? new mongoose.Types.ObjectId(conversationId.toString()) : undefined,
      formSubmissionId: formSubmissionId ? new mongoose.Types.ObjectId(formSubmissionId.toString()) : undefined,
      campaignId: campaignId ? new mongoose.Types.ObjectId(campaignId.toString()) : undefined,
      idempotencyKey,
      isAutoGenerated: true,
      createdBy: actorId ? new mongoose.Types.ObjectId(actorId) : undefined,
      metadata: { source, leadScore },
    });

    // 5. Record Creation Event
    await TaskEvent.create({
      clientId: clientObjectId,
      taskId: task._id,
      eventType: 'created',
      description: `Automated lead follow-up task created (${priority.toUpperCase()} priority, SLA deadline: ${deadline.toISOString()})`,
      newValue: {
        source,
        priority,
        slaDeadline: deadline,
        assignedTo: assignedUserId?.toString(),
      },
      actorId: actorId ? new mongoose.Types.ObjectId(actorId) : undefined,
      actorName: 'System (Auto-Intake Engine)',
    });

    logger.info(`Automated follow-up task ${task._id} created for lead ${leadObjectId} (${priority})`);
    return task;
  }
}
