import { apiClient, ApiResponse } from './api';

export type TaskType = 'call' | 'email' | 'meeting' | 'follow_up' | 'review' | 'other';
export type TaskStatus = 'open' | 'in_progress' | 'completed' | 'cancelled' | 'snoozed';
export type TaskPriority = 'low' | 'normal' | 'high' | 'urgent';

export interface TaskItem {
  _id: string;
  clientId: string;
  title: string;
  description?: string;
  taskType: TaskType;
  status: TaskStatus;
  priority: TaskPriority;
  dueAt: string;
  slaDeadline: string;
  slaBreached: boolean;
  slaBreachedAt?: string;
  slaTargetMinutes: number;
  leadId?: {
    _id: string;
    firstName: string;
    lastName?: string;
    email?: string;
    phone?: string;
    stage?: string;
  } | string;
  contactId?: {
    _id: string;
    firstName: string;
    lastName?: string;
    email?: string;
    phone?: string;
  } | string;
  conversationId?: {
    _id: string;
    channel?: string;
    subject?: string;
  } | string;
  formSubmissionId?: string;
  campaignId?: {
    _id: string;
    name?: string;
    platform?: string;
  } | string;
  assignedTo?: {
    _id: string;
    name: string;
    email: string;
  } | null;
  completedBy?: {
    _id: string;
    name: string;
    email: string;
  } | null;
  completedAt?: string;
  completionNotes?: string;
  disposition?: string;
  isAutoGenerated: boolean;
  idempotencyKey?: string;
  snoozedUntil?: string;
  snoozeReason?: string;
  metadata?: Record<string, any>;
  createdAt: string;
  updatedAt: string;
}

export interface TaskEventItem {
  _id: string;
  taskId: string;
  clientId: string;
  eventType: string;
  actor?: {
    id?: string;
    name?: string;
    email?: string;
  };
  previousState?: Record<string, any>;
  newState?: Record<string, any>;
  notes?: string;
  createdAt: string;
}

export interface TaskDispositionItem {
  _id: string;
  code: string;
  name: string;
  description?: string;
  defaultFollowUpHours?: number;
  defaultStageUpdate?: string;
  requiresFollowUp: boolean;
  isSystem: boolean;
  isActive: boolean;
}

export interface SlaPolicyItem {
  _id: string;
  clientId: string;
  name: string;
  isDefault: boolean;
  urgentTargetMinutes: number;
  highTargetMinutes: number;
  normalTargetMinutes: number;
  lowTargetMinutes: number;
  businessHoursOnly: boolean;
  escalationEmail?: string;
  createdAt: string;
  updatedAt: string;
}

export interface TaskKpis {
  openTasks: number;
  inProgressTasks: number;
  dueToday: number;
  overdueTasks: number;
  slaBreachedTasks: number;
  completedToday: number;
  avgResponseMinutes: number;
}

export interface DailyAgenda {
  overdue: TaskItem[];
  dueToday: TaskItem[];
  dueTomorrow: TaskItem[];
  upcoming: TaskItem[];
}

export interface TaskFilters {
  page?: number;
  limit?: number;
  status?: TaskStatus | 'all';
  priority?: TaskPriority | 'all';
  taskType?: TaskType | 'all';
  assignedTo?: string | 'all';
  leadId?: string;
  contactId?: string;
  conversationId?: string;
  slaBreached?: 'true' | 'false' | 'all';
  dueFrom?: string;
  dueTo?: string;
  search?: string;
}

// -------------------------------------------------------------
// Tasks API Client
// -------------------------------------------------------------

export const getTasksApi = async (filters: TaskFilters = {}) => {
  const query = new URLSearchParams();
  if (filters.page) query.set('page', filters.page.toString());
  if (filters.limit) query.set('limit', filters.limit.toString());
  if (filters.status && filters.status !== 'all') query.set('status', filters.status);
  if (filters.priority && filters.priority !== 'all') query.set('priority', filters.priority);
  if (filters.taskType && filters.taskType !== 'all') query.set('taskType', filters.taskType);
  if (filters.assignedTo && filters.assignedTo !== 'all') query.set('assignedTo', filters.assignedTo);
  if (filters.leadId) query.set('leadId', filters.leadId);
  if (filters.contactId) query.set('contactId', filters.contactId);
  if (filters.conversationId) query.set('conversationId', filters.conversationId);
  if (filters.slaBreached && filters.slaBreached !== 'all') query.set('slaBreached', filters.slaBreached);
  if (filters.dueFrom) query.set('dueFrom', filters.dueFrom);
  if (filters.dueTo) query.set('dueTo', filters.dueTo);
  if (filters.search) query.set('search', filters.search);

  const res = await apiClient.get<ApiResponse<{ tasks: TaskItem[]; pagination: { total: number; page: number; limit: number; totalPages: number } }>>(
    `/tasks?${query.toString()}`
  );
  return res.data;
};

export const getTaskKpisApi = async () => {
  const res = await apiClient.get<ApiResponse<TaskKpis>>('/tasks/kpis');
  return res.data.data!;
};

export const getAgendaApi = async () => {
  const res = await apiClient.get<ApiResponse<DailyAgenda>>('/tasks/agenda');
  return res.data.data!;
};

export const getOverdueTasksApi = async () => {
  const res = await apiClient.get<ApiResponse<TaskItem[]>>('/tasks/overdue');
  return res.data.data!;
};

export const getSlaBreachedTasksApi = async () => {
  const res = await apiClient.get<ApiResponse<TaskItem[]>>('/tasks/sla-breached');
  return res.data.data!;
};

export const getDispositionsApi = async () => {
  const res = await apiClient.get<ApiResponse<TaskDispositionItem[]>>('/tasks/dispositions');
  return res.data.data!;
};

export const getSlaPoliciesApi = async () => {
  const res = await apiClient.get<ApiResponse<SlaPolicyItem[]>>('/tasks/sla-policies');
  return res.data.data!;
};

export const updateSlaPolicyApi = async (id: string, data: Partial<SlaPolicyItem>) => {
  const res = await apiClient.put<ApiResponse<SlaPolicyItem>>(`/tasks/sla-policies/${id}`, data);
  return res.data.data!;
};

export const createTaskApi = async (data: {
  title: string;
  description?: string;
  taskType?: TaskType;
  priority?: TaskPriority;
  dueAt: string;
  assignedTo?: string;
  leadId?: string;
  contactId?: string;
  conversationId?: string;
  formSubmissionId?: string;
  campaignId?: string;
  metadata?: Record<string, any>;
}) => {
  const res = await apiClient.post<ApiResponse<TaskItem>>('/tasks', data);
  return res.data.data!;
};

export const getTaskByIdApi = async (id: string) => {
  const res = await apiClient.get<ApiResponse<TaskItem>>(`/tasks/${id}`);
  return res.data.data!;
};

export const updateTaskApi = async (id: string, data: Partial<TaskItem>) => {
  const res = await apiClient.put<ApiResponse<TaskItem>>(`/tasks/${id}`, data);
  return res.data.data!;
};

export const assignTaskApi = async (id: string, assignedTo: string | null, reason?: string) => {
  const res = await apiClient.patch<ApiResponse<TaskItem>>(`/tasks/${id}/assign`, { assignedTo, reason });
  return res.data.data!;
};

export const updatePriorityApi = async (id: string, priority: TaskPriority, reason?: string) => {
  const res = await apiClient.patch<ApiResponse<TaskItem>>(`/tasks/${id}/priority`, { priority, reason });
  return res.data.data!;
};

export const updateDueDateApi = async (id: string, dueAt: string, reason?: string) => {
  const res = await apiClient.patch<ApiResponse<TaskItem>>(`/tasks/${id}/due-date`, { dueAt, reason });
  return res.data.data!;
};

export const startTaskApi = async (id: string) => {
  const res = await apiClient.post<ApiResponse<TaskItem>>(`/tasks/${id}/start`);
  return res.data.data!;
};

export const completeTaskApi = async (id: string, completionNotes?: string) => {
  const res = await apiClient.post<ApiResponse<TaskItem>>(`/tasks/${id}/complete`, { completionNotes });
  return res.data.data!;
};

export const cancelTaskApi = async (id: string, reason?: string) => {
  const res = await apiClient.post<ApiResponse<TaskItem>>(`/tasks/${id}/cancel`, { reason });
  return res.data.data!;
};

export const snoozeTaskApi = async (id: string, snoozedUntil: string, reason?: string) => {
  const res = await apiClient.post<ApiResponse<TaskItem>>(`/tasks/${id}/snooze`, { snoozedUntil, reason });
  return res.data.data!;
};

export const applyDispositionApi = async (
  id: string,
  data: {
    disposition: string;
    notes?: string;
    scheduleFollowUp?: boolean;
    followUpDueAt?: string;
    followUpTitle?: string;
    followUpType?: TaskType;
    updateLeadStage?: string;
  }
) => {
  const res = await apiClient.post<ApiResponse<{ task: TaskItem; followUpTask?: TaskItem }>>(`/tasks/${id}/disposition`, data);
  return res.data.data!;
};

export const getTaskEventsApi = async (id: string) => {
  const res = await apiClient.get<ApiResponse<TaskEventItem[]>>(`/tasks/${id}/events`);
  return res.data.data!;
};
